export const testData = [
  {
    name: 'Название бумаги',
    cost: 1000,
    index: 'IMOEX',
    image: require('../../../assets/images/ruble.png'),
    delta: '0.05%',
    description: 'Ценная бумага, покупай быстрее!',
    country: 'США',
  },
  {
    name: 'Название бумаги',
    cost: 1000,
    index: 'IMOEX',
    image: require('../../../assets/images/ruble.png'),
    delta: '0.05%',
    description: 'Ценная бумага, покупай быстрее!',
    country: 'США',
  },
  {
    name: 'Название бумаги',
    cost: 1000,
    index: 'IMOEX',
    image: require('../../../assets/images/ruble.png'),
    delta: '0.05%',
    description: 'Ценная бумага, покупай быстрее!',
    country: 'США',
  },
  {
    name: 'Абоба',
    cost: 1000,
    index: 'IMOEX',
    image: require('../../../assets/images/ruble.png'),
    delta: '0.05%',
    description: 'Абоба',
    country: 'США',
  },
];
